def create_all_flows_scenario(scen, y, mfa_plastics_ch, mycursor):

    # create flows

    # to use and from use to separate collections
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0006', 'pr0008', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0007', 'pr0008', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0009', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0010', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0011', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0012', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0013', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0014', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0015', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0016', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0033', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0034', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0035', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0036', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0052', scen, y))

    # from use to energy recovery
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0029', scen, y))

    # from use to export or unknown destiny
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0002', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0008', 'pr0003', scen, y))

    # from separate collections to sorting
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0009', 'pr0020', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0010', 'pr0017', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0010', 'pr0021', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0010', 'pr0022', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0011', 'pr0023', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0012', 'pr0017', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0013', 'pr0017', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0014', 'pr0022', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0016', 'pr0017', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0016', 'pr0019', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0016', 'pr0022', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0016', 'pr0031', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0033', 'pr0019', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0033', 'pr0022', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0033', 'pr0037', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0034', 'pr0039', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0035', 'pr0040', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0036', 'pr0041', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0052', 'pr0053', scen, y))

    # from sorting to recycling
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0017', 'pr0026', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0017', 'pr0028', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0017', 'pr0030', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0017', 'pr0042', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0019', 'pr0026', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0019', 'pr0028', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0019', 'pr0030', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0019', 'pr0042', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0020', 'pr0026', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0020', 'pr0027', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0020', 'pr0029', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0020', 'pr0031', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0021', 'pr0026', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0021', 'pr0027', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0021', 'pr0029', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0021', 'pr0031', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0022', 'pr0027', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0022', 'pr0029', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0022', 'pr0031', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0022', 'pr0043', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0023', 'pr0027', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0023', 'pr0029', scen, y))
    # mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0023', 'pr0031', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0037', 'pr0042', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0037', 'pr0044', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0037', 'pr0045', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0037', 'pr0046', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0039', 'pr0027', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0039', 'pr0044', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0040', 'pr0048', scen, y))
    mycursor.callproc('create_flows_pr_to_pr_scen', ('pr0041', 'pr0051', scen, y))

    mfa_plastics_ch.commit()
